Fix load_state_dict function
Following error fixed

pytorch_model.bin: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 501M/501M [00:01<00:00, 359MB/s]
Some weights of the model checkpoint at roberta-base were not used when initializing RobertaModel: ['lm_head.dense.bias', 'lm_head.decoder.weight', 'lm_head.bias', 'lm_head.layer_norm.weight', 'lm_head.l
ayer_norm.bias', 'lm_head.dense.weight']
- This IS expected if you are initializing RobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a
 BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequen
ceClassification model).
Traceback (most recent call last):
  File "/local/home/korenard/AudioSep/run_model.py", line 2, in <module>
    from pipeline import build_audiosep, separate_audio
  File "/local/home/korenard/AudioSep/pipeline.py", line 7, in <module>
    from utils import ignore_warnings, parse_yaml, load_ss_model
  File "/local/home/korenard/AudioSep/utils.py", line 12, in <module>
    from models.audiosep import AudioSep, get_model_class   
  File "/local/home/korenard/AudioSep/models/audiosep.py", line 14, in <module>
    class AudioSep(pl.LightningModule, PyTorchModelHubMixin):
  File "/local/home/korenard/AudioSep/models/audiosep.py", line 19, in AudioSep
    query_encoder: nn.Module = CLAP_Encoder().eval(),
  File "/local/home/korenard/AudioSep/models/clap_encoder.py", line 28, in __init__
    self.model, self.model_cfg = create_model(
  File "/local/home/korenard/AudioSep/models/CLAP/open_clip/factory.py", line 152, in create_model
    ckpt = load_state_dict(checkpoint_path, skip_params=True)
  File "/local/home/korenard/AudioSep/models/CLAP/open_clip/factory.py", line 55, in load_state_dict
    checkpoint = torch.load(checkpoint_path, map_location=map_location)
  File "/home/korenard/.pyenv/versions/3.10.16/envs/audiosep/lib/python3.10/site-packages/torch/serialization.py", line 1470, in load
    raise pickle.UnpicklingError(_get_wo_message(str(e))) from None
_pickle.UnpicklingError: Weights only load failed. This file can still be loaded, to do so you have two options, do those steps only if you trust the source of the checkpoint.
        (1) In PyTorch 2.6, we changed the default value of the `weights_only` argument in `torch.load` from `False` to `True`. Re-running `torch.load` with `weights_only` set to `False` will likely succ
eed, but it can result in arbitrary code execution. Do it only if you got the file from a trusted source.
        (2) Alternatively, to load with `weights_only=True` please check the recommended steps in the following error message.
        WeightsUnpickler error: Unsupported global: GLOBAL numpy.core.multiarray.scalar was not an allowed global by default. Please use `torch.serialization.add_safe_globals([scalar])` or the `torch.ser
ialization.safe_globals([scalar])` context manager to allowlist this global if you trust this class/function.

Check the documentation of torch.load to learn more about types accepted by default with weights_only https://pytorch.org/docs/stable/generated/torch.load.html.
(audiosep)